"""Tests for the balanced-element watermark remover.

Fixtures mirror real nesting styles across producers:
  A. flat <div> wrapping the link            (OceanofPDF, fixed-layout image books)
  B. <div> holding the link plus an empty sibling <div>   (OceanofPDF)
  C. <a> inside <h1> inside a content <div> that also holds real text (OceanofPDF)
  D. <b> stamp whose text splits across the <b> and the <a>  (ABC Amber LIT Converter)
  G/H. unclosed stamp anchors that swallow prose out to an unrelated </a>
       (reported 2026-09-08; the fallback must refuse them, so they are
       intentionally the only fixtures that are not valid XML)
Each fixture is valid XML so the cleaned output can be re-parsed to prove it stays
well-formed (the bug that motivated balanced matching produced unparsable XML),
except where a fixture's own point is a broken book the pass must refuse to touch.
"""

import unittest
import xml.etree.ElementTree as ET

from bindery.watermark import strip_watermark_html

DOC = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    '<html xmlns="http://www.w3.org/1999/xhtml"><body>\n{body}\n</body></html>'
)

# A: flat wrapper, watermark is the whole page tail.
FLAT = (
    "<p>Real text.</p>"
    '<div style="text-align:center;"><p><a href="https://oceanofpdf.com">'
    "<i>OceanofPDF.com</i></a></p></div>"
)

# B: wrapper holds the watermark <p> AND an empty sibling <div>.
EMPTY_SIBLING = (
    "<p>Real text.</p>"
    '<div class="calibre2"><p class="calibre3">'
    '<a href="http://oceanofpdf.com" class="calibre4"><i>OceanofPDF.com</i></a></p>'
    '<div class="calibre6"></div></div>'
)

# C: <a> inside <h1> inside a content div that also wraps a real dedication <p>.
HEADING = (
    '<div class="frame"><p class="dedi">To those on their own paths</p>'
    '<div class="calibre5"><h1 class="calibre6">'
    '<a href="http://oceanofpdf.com">OceanofPDF.com</a></h1></div></div>'
)

# Watermark embedded inline in a paragraph of real prose (only the <a> should go).
INLINE = (
    '<p>Read more at <a href="https://oceanofpdf.com">OceanofPDF.com</a> today.</p>'
)

# D: ABC Amber LIT Converter stamp. The word "Converter" is split across the <b>
# text and the <a> ("...Conv" + "erter..."), so removing only the <a> would orphan
# "Generated by ABC Amber LIT Conv". The <b> is the wrapper whose visible text
# equals the watermark, so the whole <b> goes.
ABC_AMBER = (
    "<p>Real chapter text.</p>"
    '<b class="calibre1">Generated by ABC Amber LIT Conv'
    '<a href="http://www.processtext.com/abclit.html">'
    "erter, http://www.processtext.com/abclit.html</a></b>"
)

# A real <b> phrase that merely sits near the watermark must survive: only the
# watermark <b> (the one whose entire text is the stamp) is eligible for removal.
BOLD_PROSE = (
    "<p>She said <b>absolutely not</b>.</p>"
    "<b>Generated by ABC Amber LIT Conv"
    '<a href="http://www.processtext.com/abclit.html">'
    "erter, http://www.processtext.com/abclit.html</a></b>"
)

# Both producers' stamps in one document; the registry handles each.
MIXED = FLAT + "<p>Body.</p>" + ABC_AMBER

# E: anchorless ABC Amber. The stamp is plain text with the URL NOT linked, and it
# repeats. There is no <a> to anchor on, so the text pass finds it and removes the
# <p> whose whole text is the (repeated) stamp. (Real form: Jack Ketchum Off Season.)
ABC_AMBER_TEXT = (
    "<p>Real chapter text.</p>"
    '<p class="calibre3">ABC Amber LIT Converter '
    "http://www.processtext.com/abclit.html ABC Amber LIT Converter "
    "http://www.processtext.com/abclit.html</p>"
)

# F: anchorless ABC Amber nested in a FOOTER div; the outermost wrapper whose whole
# text is the stamp is the <div>, so it goes entirely. (Real form: Julia Quinn.)
ABC_AMBER_FOOTER = (
    "<p>Story.</p>"
    '<div type="FOOTER" class="calibre1"><p lang="en-US" class="western3">'
    "<span>ABC Amber LIT Converter\n\thttp://www.processtext.com/abclit.html"
    "</span></p></div>"
)

# Safety: a real sentence that merely mentions the URL must survive. Its wrapper's
# text is not ONLY the stamp, so the text pass removes nothing.
URL_IN_PROSE = (
    "<p>The file was made with a tool at "
    "http://www.processtext.com/abclit.html, years ago.</p>"
)

# G: an unclosed stamp anchor, the reported failure shape. The stamp <a> never
# closes, so the DOTALL regex matches through two paragraphs of real prose to
# the next unrelated </a>; the old whole-match fallback deleted all of it with
# count 1. The fallback must refuse: nothing is removed, the refusal is
# reported, and every paragraph survives.
UNCLOSED_ANCHOR = (
    "<p>Real chapter text.</p>"
    '<a href="https://oceanofpdf.com">OceanofPDF.com</p>'
    "<p>First paragraph of real content.</p>"
    "<p>Second paragraph of real content.</p>"
    '<p>See <a href="https://example.com/other">this link</a> for more.</p>'
)

# H: an unclosed stamp anchor whose swallow happens to be tag-free prose, longer
# than any stamp. Length alone must refuse it.
UNCLOSED_ANCHOR_TAG_FREE = (
    '<a href="https://oceanofpdf.com">OceanofPDF.com and a long stretch of '
    "plain unmarked text that goes on well past any plausible stamp length, "
    "still inside the unclosed anchor, until an unrelated link closes: "
    '<a href="https://example.com/x">x</a>'
)

# I: a stamp anchor holding the stamp plus a void tag, inline in prose. Its
# visible text is exactly the watermark, so the whole match is safe to delete
# even though the body carries markup.
STAMP_WITH_MARKUP = (
    '<p>Read more at <a href="https://oceanofpdf.com">OceanofPDF.com<br></a> today.</p>'
)


def parse(html: str) -> ET.Element:
    """Re-parse to assert well-formedness; returns the root element."""
    return ET.fromstring(html)


class TestRemoval(unittest.TestCase):
    def _clean(self, body: str):
        html = DOC.format(body=body)
        cleaned, n, refused = strip_watermark_html(html)
        return cleaned, n, refused

    def test_flat_wrapper_removed_whole(self):
        cleaned, n, refused = self._clean(FLAT)
        self.assertEqual(n, 1)
        self.assertNotIn("oceanofpdf", cleaned.lower())
        self.assertIn("Real text.", cleaned)
        self.assertNotIn("<div", cleaned)  # the watermark div is gone entirely
        parse(cleaned)

    def test_empty_sibling_wrapper_removed_whole(self):
        cleaned, n, refused = self._clean(EMPTY_SIBLING)
        self.assertEqual(n, 1)
        self.assertNotIn("oceanofpdf", cleaned.lower())
        self.assertIn("Real text.", cleaned)
        # both the watermark div and its empty calibre6 sibling go with the wrapper
        self.assertNotIn("calibre", cleaned)
        parse(cleaned)

    def test_heading_wrapper_preserves_real_dedication(self):
        cleaned, n, refused = self._clean(HEADING)
        self.assertEqual(n, 1)
        self.assertNotIn("oceanofpdf", cleaned.lower())
        # the real dedication text and its outer frame must survive
        self.assertIn("To those on their own paths", cleaned)
        self.assertIn('<div class="frame">', cleaned)
        self.assertNotIn("calibre5", cleaned)  # the pure-watermark inner div is gone
        parse(cleaned)

    def test_inline_link_only_removes_anchor(self):
        cleaned, n, refused = self._clean(INLINE)
        self.assertEqual(n, 1)
        self.assertNotIn("oceanofpdf", cleaned.lower())
        # surrounding prose and its paragraph must remain
        self.assertIn("Read more at", cleaned)
        self.assertIn("today.", cleaned)
        self.assertIn("<p>", cleaned)
        parse(cleaned)

    def test_idempotent(self):
        cleaned, _, _ = self._clean(EMPTY_SIBLING)
        again, n, refused = strip_watermark_html(cleaned)
        self.assertEqual(n, 0)
        self.assertEqual(refused, 0)
        self.assertEqual(again, cleaned)

    def test_no_watermark_is_noop(self):
        html = DOC.format(body="<p>Just a normal page.</p>")
        cleaned, n, refused = strip_watermark_html(html)
        self.assertEqual(n, 0)
        self.assertEqual(refused, 0)
        self.assertEqual(cleaned, html)

    def test_multiple_watermarks_in_one_doc(self):
        body = FLAT + "<p>Middle.</p>" + EMPTY_SIBLING
        cleaned, n, refused = self._clean(body)
        self.assertEqual(n, 2)
        self.assertNotIn("oceanofpdf", cleaned.lower())
        self.assertIn("Middle.", cleaned)
        parse(cleaned)

    def test_abc_amber_bold_wrapper_removed_whole(self):
        cleaned, n, refused = self._clean(ABC_AMBER)
        self.assertEqual(n, 1)
        self.assertNotIn("processtext", cleaned.lower())
        self.assertNotIn("abc amber", cleaned.lower())
        self.assertNotIn("Generated by", cleaned)  # no orphaned half-phrase
        self.assertIn("Real chapter text.", cleaned)
        self.assertNotIn("calibre1", cleaned)  # the watermark <b> is gone entirely
        parse(cleaned)

    def test_abc_amber_preserves_real_bold(self):
        cleaned, n, refused = self._clean(BOLD_PROSE)
        self.assertEqual(n, 1)
        self.assertNotIn("processtext", cleaned.lower())
        self.assertNotIn("Generated by", cleaned)
        # the real bold phrase and its text survive intact
        self.assertIn("<b>absolutely not</b>", cleaned)
        parse(cleaned)

    def test_mixed_producers_in_one_doc(self):
        cleaned, n, refused = self._clean(MIXED)
        self.assertEqual(n, 2)
        self.assertNotIn("oceanofpdf", cleaned.lower())
        self.assertNotIn("processtext", cleaned.lower())
        self.assertIn("Body.", cleaned)
        parse(cleaned)

    def test_anchorless_text_paragraph_removed(self):
        cleaned, n, refused = self._clean(ABC_AMBER_TEXT)
        self.assertEqual(n, 1)  # one wrapper, even though the stamp repeats inside
        self.assertNotIn("processtext", cleaned.lower())
        self.assertNotIn("ABC Amber", cleaned)
        self.assertIn("Real chapter text.", cleaned)
        self.assertNotIn("calibre3", cleaned)  # the watermark <p> is gone
        parse(cleaned)

    def test_anchorless_footer_div_removed_whole(self):
        cleaned, n, refused = self._clean(ABC_AMBER_FOOTER)
        self.assertEqual(n, 1)
        self.assertNotIn("processtext", cleaned.lower())
        self.assertNotIn("FOOTER", cleaned)  # the whole footer div is gone
        self.assertIn("Story.", cleaned)
        parse(cleaned)

    def test_url_in_real_prose_is_preserved(self):
        cleaned, n, refused = self._clean(URL_IN_PROSE)
        self.assertEqual(n, 0)  # wrapper text is not ONLY the stamp
        self.assertIn("processtext", cleaned.lower())  # real sentence kept intact
        self.assertIn("years ago.", cleaned)
        parse(cleaned)

    def test_unclosed_anchor_refused_not_deleted(self):
        cleaned, n, refused = self._clean(UNCLOSED_ANCHOR)
        # the whole-match fallback used to swallow both paragraphs with count 1
        self.assertEqual(n, 0)
        self.assertEqual(refused, 1)
        self.assertIn("Real chapter text.", cleaned)
        self.assertIn("First paragraph of real content.", cleaned)
        self.assertIn("Second paragraph of real content.", cleaned)
        self.assertIn("this link", cleaned)  # the unrelated </a> is untouched
        # no parse(cleaned) here: the refusal leaves the book exactly as broken
        # as it arrived (the unclosed anchor is the pre-existing defect)

    def test_unclosed_anchor_with_tag_free_prose_refused(self):
        cleaned, n, refused = self._clean(UNCLOSED_ANCHOR_TAG_FREE)
        # no tags inside the swallow, but it runs far past any stamp length
        self.assertEqual(n, 0)
        self.assertEqual(refused, 1)
        self.assertIn("plain unmarked text", cleaned)

    def test_inline_stamp_with_void_markup_still_removed(self):
        cleaned, n, refused = self._clean(STAMP_WITH_MARKUP)
        # visible text is exactly the stamp, so the whole match is safe
        self.assertEqual(n, 1)
        self.assertEqual(refused, 0)
        self.assertNotIn("oceanofpdf", cleaned.lower())
        self.assertIn("Read more at", cleaned)
        self.assertIn("today.", cleaned)
        parse(cleaned)

    def test_refusal_does_not_block_later_safe_removal(self):
        body = UNCLOSED_ANCHOR + "<p>Middle.</p>" + INLINE
        cleaned, n, refused = self._clean(body)
        self.assertEqual(n, 1)  # the well-formed inline stamp still goes
        self.assertEqual(refused, 1)  # the unclosed one is reported once
        self.assertIn("First paragraph of real content.", cleaned)
        self.assertNotIn("oceanofpdf.com</a>", cleaned.lower())


if __name__ == "__main__":
    unittest.main()
