"""Locate and remove producer/conversion watermarks from (X)HTML documents.

A watermark is a run of markup whose visible text is a known producer stamp.
Producers inject it two ways, and oceanstrip handles both with the same
balanced-element removal so a well-formed document stays well-formed:

- **Anchored** (a link): an <a> whose start tag (href) carries a known signature.
  OceanofPDF appends `<a href="...oceanofpdf.com">OceanofPDF.com</a>`; ABC Amber
  wraps `<b>Generated by ABC Amber LIT Conv<a href="...processtext...">erter,
  ...</a></b>` (the word "Converter" straddles the tag boundary). We find the <a>,
  walk up to the OUTERMOST enclosing wrapper whose entire visible text is the
  watermark, and delete that whole balanced element. If no such clean wrapper
  exists (the link sits inline in real prose), only the <a> is removed.

- **Anchorless** (plain text): the stamp is literal text with the URL not linked,
  e.g. `<p>ABC Amber LIT Converter http://www.processtext.com/abclit.html</p>` or a
  `<div type="FOOTER"><p><span>...</span></p></div>`. There is no <a> to anchor on,
  so we locate the stamp by a text signature and walk up to the outermost wrapper
  whose entire visible text is the watermark (allowing the stamp to repeat), then
  delete it. Real prose that merely mentions the URL is safe: its wrapper's text is
  not *only* the watermark, so nothing is removed.

A flat regex cannot do either safely: it closes on the wrong tag and corrupts the
XML, or orphans the half of a phrase that sits outside the <a>. New producers are
one entry in WATERMARKS; the passes below are otherwise signature-agnostic.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field


@dataclass(frozen=True)
class Watermark:
    """A known producer watermark.

    - ``href_sig``: lowercase substring expected in an anchored watermark's <a>
      start tag (its href), or None if this producer never links the stamp.
    - ``text_sig``: a lowercase substring of the stamp's *visible text* used to
      locate an anchorless occurrence cheaply (e.g. "processtext.com/abclit").
    - ``phrase``: a regex (case-insensitive) matching one occurrence of the stamp's
      full visible text. A wrapper is removed only when its entire normalized text
      is one or more repetitions of this phrase, which is what keeps real prose that
      merely sits near the stamp untouched.

    ``anchor`` and ``pure`` are the compiled patterns, built in __post_init__.
    """

    name: str
    href_sig: str | None
    text_sig: str
    phrase: str
    anchor: re.Pattern[str] | None = field(default=None, compare=False)
    pure: re.Pattern[str] = field(default=None, compare=False)  # type: ignore[assignment]

    def __post_init__(self) -> None:
        anchor = (
            re.compile(
                rf"<a\b[^>]*?{re.escape(self.href_sig)}[^>]*?>.*?</a>",
                re.IGNORECASE | re.DOTALL,
            )
            if self.href_sig
            else None
        )
        object.__setattr__(self, "anchor", anchor)
        object.__setattr__(
            self, "pure", re.compile(rf"(?:{self.phrase}\s*)+", re.IGNORECASE)
        )


# The known watermarks. Append here to support a new producer; nothing else changes.
WATERMARKS: tuple[Watermark, ...] = (
    Watermark(
        name="OceanofPDF",
        href_sig="oceanofpdf",
        text_sig="oceanofpdf.com",
        phrase=r"oceanofpdf\.com",
    ),
    Watermark(
        name="ABC Amber LIT Converter",
        href_sig="processtext",
        text_sig="processtext.com/abclit",
        phrase=r"(?:generated by )?abc amber lit converter,?\s*"
        r"https?://(?:www\.)?processtext\.com/abclit\.html",
    ),
)

# Any tag (open / close / self-closing), used for the balanced-element walk.
TAG = re.compile(r"<(/?)([a-zA-Z][\w:-]*)\b[^>]*?(/?)>", re.DOTALL)

# HTML void elements never have a closing tag; ignore them in balance tracking.
VOID = {
    "area",
    "base",
    "br",
    "col",
    "embed",
    "hr",
    "img",
    "input",
    "link",
    "meta",
    "param",
    "source",
    "track",
    "wbr",
}

# Removable watermark wrappers. Never body/html/section, so a page whose sole *text*
# is the watermark (e.g. an image-only title page) is not deleted wholesale. The
# inline elements (b/i/em/strong) are here because ABC Amber wraps its stamp in a
# <b>; the "visible text is only the watermark" guard below keeps the wider set
# safe: a real heading/paragraph/bold phrase won't have text that is a watermark.
WRAPPERS = {
    "div",
    "p",
    "span",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "b",
    "i",
    "em",
    "strong",
}

# If a candidate wrapper contains any of these it holds real content. don't remove.
MEDIA = re.compile(
    r"<(?:img|image|svg|video|audio|picture|iframe|table|object)\b", re.IGNORECASE
)


def _norm(element: str) -> str:
    """Visible text of an element fragment: tags stripped, nbsp and whitespace runs
    collapsed to single spaces, stripped, lowercased."""
    text = re.sub(r"<[^>]+>", "", element).replace("\xa0", " ")
    return re.sub(r"\s+", " ", text).strip().lower()


def _matching_close(html: str, name: str, open_end: int) -> tuple[int, int] | None:
    """Span of the close tag matching a `name` element already opened just before
    `open_end` (which must point past that opening tag's '>')."""
    depth = 1
    pat = re.compile(
        rf"<(/?)({re.escape(name)})\b[^>]*?(/?)>", re.IGNORECASE | re.DOTALL
    )
    for m in pat.finditer(html, open_end):
        closing, _, selfclose = m.group(1), m.group(2), m.group(3)
        if selfclose:
            continue
        if closing:
            depth -= 1
            if depth == 0:
                return m.start(), m.end()
        else:
            depth += 1
    return None


def _ancestors(html: str, a_start: int, a_end: int):
    """Yield (open_start, close_end) for wrapper elements enclosing [a_start, a_end],
    outermost first."""
    stack: list[tuple[str, int, int]] = []
    for m in TAG.finditer(html, 0, a_start):
        closing, name, selfclose = m.group(1), m.group(2).lower(), m.group(3)
        if name in VOID or selfclose:
            continue
        if closing:
            for i in range(len(stack) - 1, -1, -1):
                if stack[i][0] == name:
                    del stack[i:]
                    break
        else:
            stack.append((name, m.start(), m.end()))

    for name, ostart, oend in stack:
        if name not in WRAPPERS:
            continue
        close = _matching_close(html, name, oend)
        if close and close[0] >= a_end:
            yield ostart, close[1]


def _pure_wrapper_span(
    html: str, start: int, end: int, wm: Watermark
) -> tuple[int, int] | None:
    """The outermost wrapper enclosing [start, end] whose entire visible text is the
    watermark (one or more repetitions) and which holds no media; else None."""
    for ostart, cend in _ancestors(html, start, end):  # outermost first
        element = html[ostart:cend]
        if MEDIA.search(element):
            continue
        if wm.pure.fullmatch(_norm(element)):
            return ostart, cend
    return None


def _strip_anchored(html: str, wm: Watermark) -> tuple[str, int]:
    """Remove anchored (linked) occurrences of `wm`. Deletes the outermost pure
    wrapper around each watermark <a>, or the <a> itself when it sits inline."""
    if wm.anchor is None:
        return html, 0
    count = 0
    while (m := wm.anchor.search(html)) is not None:
        span = _pure_wrapper_span(html, m.start(), m.end(), wm)
        s, e = span if span else (m.start(), m.end())
        html = html[:s] + html[e:]
        count += 1
    return html, count


def _strip_text(html: str, wm: Watermark) -> tuple[str, int]:
    """Remove anchorless (plain-text) occurrences of `wm`. Finds the stamp by its
    text signature and deletes the outermost wrapper whose whole text is the
    watermark; an occurrence with no such wrapper (the URL sits in real prose) is
    left untouched."""
    count = 0
    pos = 0
    while (i := html.lower().find(wm.text_sig, pos)) != -1:
        span = _pure_wrapper_span(html, i, i + len(wm.text_sig), wm)
        if span is None:
            pos = i + len(wm.text_sig)  # not a pure watermark wrapper; skip it
            continue
        html = html[: span[0]] + html[span[1] :]
        count += 1
        pos = 0
    return html, count


def strip_watermark_html(html: str) -> tuple[str, int]:
    """Remove every known watermark (anchored and anchorless) from one document.

    Returns (cleaned_html, number_of_watermarks_removed).
    """
    total = 0
    for wm in WATERMARKS:
        html, n_anchor = _strip_anchored(html, wm)
        html, n_text = _strip_text(html, wm)
        total += n_anchor + n_text
    return html, total
